### ISSUE TITLE
Getting same error in different testing projects VS 2013

### ISSUE THREAD

**Issue by rahulm15** [OpenCoverUI/OpenCover.UI#125]
Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at OpenCover.UI.Processors.NUnitTestExecutor.ReadTestCase(XElement ts)
   at OpenCover.UI.Processors.NUnitTestExecutor.<ReadTestResults>b__1(XElement ts)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__88`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.<JoinIterator>d__61`4.MoveNext()
   at OpenCover.UI.Processors.NUnitTestExecutor.UpdateTestMethodsExecution(IEnumerable`1 tests)
   at OpenCover.UI.Commands.ExecuteSelectedTestsCommand.<RunOpenCover>b__1()

**Comment by pver** [comment]
Something seems to go wrong while reading the test results. 
What version of NUnit are you using (not the dll version referenced in your test project, but the version of NUnit you configured for use by OpenCover.UI)?

**Comment by ashes999** [comment]
This looks like a duplicate of #42 

I get the same stack dump today. I'm using NUnit 2.6.4 (latest 2.x prod version), with OpenCover configured to use `nunit-console.exe`
