### ISSUE TITLE
Exception during run UT with TestCaseSource

### ISSUE THREAD

**Issue by comradum** [OpenCoverUI/OpenCover.UI#146]
### Issue description:
Have exception: "Length cannot be less than zero" when start UT with TestCaseSource:

Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at OpenCover.UI.Processors.NUnitTestExecutor.ReadTestCase(XElement ts)
   at OpenCover.UI.Processors.NUnitTestExecutor.<ReadTestResults>b__1(XElement ts)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.<JoinIterator>d__37`4.MoveNext()
   at OpenCover.UI.Processors.NUnitTestExecutor.UpdateTestMethodsExecution(IEnumerable`1 tests)
   at OpenCover.UI.Commands.ExecuteSelectedTestsCommand.<RunOpenCover>b__1()

### Versions used:
- OpenCover exe: 4.6.519
- OpenCover.UI: 0.8.1
- Visual Studio (inc. SP number): VS 2012 11.0.61219.00 Update 5
- MsTest/NUnit/xUnit: NUnit: 2.6.4

**Comment by MelleKoning** [comment]
Can you show the testclass source that causes this exception? OpenCover.UI has unit tests to ensure discovery of tests work, so we might have missed your test scenario?

**Comment by comradum** [comment]
Please:

using GcmSetup.TestSetup.Pages.ResultFields.Ranges;
using NUnit.Framework;
using System;
using System.Collections;
using TasklistDomain.Entities.Business;

```csharp
namespace LabResult.Tests.Tasklist.Domain.Entities.Business.ResultTest
{
   [TestFixture]
   public class TryParseNumericResult
   {
      public IEnumerable GetTestCases()
      {
         yield return
            new TestCaseData(">50").SetName("Greater than 50")
               .Returns(new Tuple<decimal?, ConditionType>(50, ConditionType.GREATER));
         yield return
            new TestCaseData("<50").SetName("Less than 50")
               .Returns(new Tuple<decimal?, ConditionType>(50, ConditionType.LESS));
         yield return
            new TestCaseData("50").SetName("Equal to 50")
               .Returns(new Tuple<decimal?, ConditionType>(50, ConditionType.EQUAL));
         yield return
            new TestCaseData("N50").SetName("Alphanumeric result result")
               .Returns(new Tuple<decimal?, ConditionType>(null, null));
      }

      [Test]
      [TestCaseSource("GetTestCases")]
      public Tuple<decimal?, ConditionType> TestTryParseNumericResult(string value)
      {
         decimal? numericValue;
         ConditionType conditionType;
         Result.TryParseNumericResult(value, out numericValue, out conditionType);
         return new Tuple<decimal?, ConditionType>(numericValue, conditionType);
      }
   }
}
```

**Comment by pver** [comment]
The same issue was reported here: #90

It might have been solved already by merging in #117 (which also already included test cases for this) Although someone reported issues with it, so we need to retest that..

**Comment by pver** [comment]
See also #42

**Comment by MelleKoning** [comment]
@comradum I implemented your testcode to try it, and it seems to work.

Had to add a few methods that were missing from your post. this is the class I eventually had:

` namespace OpenCover.UI.TestDiscoverer.TestResources.NUnit
{

    [TestFixture]
    public class DynamicTestcaseTests
    {
        public enum ConditionType
        {
            GREATER,
            LESS,
            EQUAL
        }

        public IEnumerable GetTestCases()
        {
            yield return
               new TestCaseData(">50").SetName("Greater than 50")
                  .Returns(new Tuple<decimal?, ConditionType>(50, ConditionType.GREATER));
            yield return
               new TestCaseData("<50").SetName("Less than 50")
                  .Returns(new Tuple<decimal?, ConditionType>(50, ConditionType.LESS));
            yield return
               new TestCaseData("50").SetName("Equal to 50")
                  .Returns(new Tuple<decimal?, ConditionType>(50, ConditionType.EQUAL));
            //yield return
              // new TestCaseData("N50").SetName("Alphanumeric result result")
                //  .Returns(new Tuple<decimal?, ConditionType>(null, null));
        }

        [Test]
        [TestCaseSource("GetTestCases")]
        public Tuple<decimal?, ConditionType> TestTryParseNumericResult(string value)
        {
            decimal numericValue = 50;
            ConditionType conditionType = TryParseNumericResult(value);
            return new Tuple<decimal?, ConditionType>(numericValue, conditionType);
        }

        public ConditionType TryParseNumericResult(string value)
        {
            char ch = value[0];
            if (ch == '5')
            {
                return ConditionType.EQUAL;
            }
            if (ch == '<')
            {
                return ConditionType.LESS;
            }
            return ConditionType.GREATER;
        }
    }
}`

Ran this with the latest version of OpenCover and got this on screen:

![image](https://cloud.githubusercontent.com/assets/506830/21848874/3f2f0208-d803-11e6-93d7-535fe3e12d4d.png)

So, seems to work, unless your implementation of certain methods is different. Can you try with the latest build from github?

**Comment by comradum** [comment]
Where I can found built binaries? Or I should build them myself? Also I have noticed that my problem already fixed, but I can't find any release with this problem fixed.

**Comment by comradum** [comment]
@MelleKoning, I have **release** version 0.8.1 installed. I see that after release there were commits on master that can fix my problem.

Are new release builds planned? If yes - when?

**Comment by MelleKoning** [comment]
Hi @comradum, Yes you have to build the extension from sources. @pver do you know who can warrant a release?
