### ISSUE TITLE
Length cannot be less than zero exception

### ISSUE THREAD

**Issue by pver** [OpenCoverUI/OpenCover.UI#42]
Found this one in the Q&A on the visual studio gallery:

> An exception occured: Length cannot be less than zero. Parameter name: length. Please refer to output window for more details.
I can't find the extra details it is talking about: nothing is shown in any of OpenCover's panes, or in the normal VisualStudio output pane.
...
I did some more troubleshooting and this is being caused by a specific test that looks like this:
        [TestCase(false, TestName = "FirstTestCase")]
        [TestCase(true, TestName = "SecondTestCase")]
        public void TestSomething(bool input) {
            ...
        }
Perhaps OpenCover UI is being confused by these tests being renamed by the TestName parameter to the TestCase attribute?

I did a quick test and can confirm this makes the plugin fail. The spinner ('Please wait while we collect coverage results') stays visible and a popup is shown:
![image](https://cloud.githubusercontent.com/assets/1618378/6253277/4dbc911c-b7a0-11e4-871a-e7336499bb93.png)

**Comment by pver** [comment]
Extra info logged in the OpenCover.UI output window:

> Parameter name: length
   at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at OpenCover.UI.Processors.NUnitTestExecutor.ReadTestCase(XElement ts)
   at OpenCover.UI.Processors.NUnitTestExecutor.<ReadTestResults>b__1(XElement ts)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__88`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.<JoinIterator>d__61`4.MoveNext()
   at OpenCover.UI.Processors.NUnitTestExecutor.UpdateTestMethodsExecution(IEnumerable`1 tests)
   at OpenCover.UI.Commands.ExecuteSelectedTestsCommand.<RunOpenCover>b__1()

**Comment by pver** [comment]
@sawilde I'll take care of this one: I found the root cause for the problem and have an approach to fix it

**Comment by sawilde** [comment]
feel free to assign tickets to yourself :)

**Comment by pver** [comment]
Thanks for assigning :)
I couldn't find the assign functionality myself, I think it's because assigning also requires write access to the repository?

**Comment by sawilde** [comment]
Ahh - I didn't know that, learning more about github things everyday.

I did wonder about write access but I want devs to work on their own forks and submit pull requests before I do so - I only do very minor changes on the main repo i.e. readme.md files etc

**Comment by ashes999** [comment]
Looks the same as #125 . Is there any progress on this? I'm getting an identical stack dump today.
