### ISSUE TITLE
Argument out of range near TextViewCoverageProviderBase.GetWordSpans

### ISSUE THREAD

**Issue by tekkies** [OpenCoverUI/OpenCover.UI#66]
I've seen this issue after using OpenCover.UI for an hour or so.  I've also seen the same issue on another PC in the team on another project.

	Specified argument was out of the range of valid values.
	Parameter name: length
	   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)
	   at OpenCover.UI.Helper.TextViewCoverageProviderBase.AddWordSpansForSequencePointsCoveringMultipleLines(ITextSnapshot snapshot, List`1 wordSpans, SequencePoint sequencePoint, Int32 sequencePointStartLine, Int32 sequencePointEndLine, Boolean covered)
	   at OpenCover.UI.Helper.TextViewCoverageProviderBase.GetWordSpans(ITextSnapshot snapshot)
	
Once the exception has occurred, the Menu to cover my code is greyed and I have to restart VS to get it to work again.

**Comment by tekkies** [comment]
It seems that this is coincidental and is handled fine.
