### ISSUE TITLE
Span constructor exception

### ISSUE THREAD

**Issue by pver** [OpenCoverUI/OpenCover.UI#79]
From time to time I notice these error messages in the OpenCoverUI output window (mostly at startup). 

```
Specified argument was out of the range of valid values.
Parameter name: length
   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)
   at OpenCover.UI.Helper.TextViewCoverageProviderBase.AddWordSpansForSequencePointsCoveringMultipleLines(ITextSnapshot snapshot, List`1 wordSpans, SequencePoint sequencePoint, Int32 sequencePointStartLine, Int32 sequencePointEndLine, Boolean covered)
   at OpenCover.UI.Helper.TextViewCoverageProviderBase.GetWordSpans(ITextSnapshot snapshot)
```

**Comment by pver** [comment]
Seems to be the same issue as was reported here: #66 but as mentioned by the reporter of that issues, I also see it only occassionaly
