### ISSUE TITLE
"There is an error in XML document" on <Method skippedDueTo="Unknown"...

### ISSUE THREAD

**Issue by meolus** [OpenCoverUI/OpenCover.UI#82]
I am getting an exception on running "Cover with OpenCover" from Open Cover Test Explorer:

>There is an error in XML document (1115, 21).
>   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
>   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
>   at OpenCover.UI.Processors.TestExecutor.GetExecutionResults()

At this position in test result xml I found below /CoverageSession/Modules/Module/Classes/Class/Methods/Method a "skippedDueTo="Unknown"", which seems to cause the problem.

The "class" this part of the test result depends on is a delegate:
> delegate void PortEventHandler(Port sender, PortEventArgs e);

which is used for an event:
> private event PortEventHandler _portEvent;

The Methods in rest result xml are ctor, Invoke, BeginInvoke and EndInvoke, all with "skippedDueTo="Unknown"".

**Comment by pver** [comment]
@meolus thanks for reporting this, we'll look into it! Could you include the xml file that causes the issue? Maybe it's best to do the coverage against the related test, to keep the xml file small

**Comment by meolus** [comment]
I created a new minimal console project to reproduce the problem:

Program.cs in console application project:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    public delegate void MyEventHandler(Program sender, EventArgs e);

    public class Program
    {
        public event MyEventHandler aEvent;

        static void Main(string[] args)
        {
        }
    }
}
```


UnitTest1.cs in test project:
```csharp
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ConsoleApplication1;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Program prog = new Program();
        }
    }
}
```

OpenCover Log output is:
```log
1 tests found
-target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"\"C:\temp\ConsoleApplication1\UnitTestProject1\bin\Debug\UnitTestProject1.dll\" /Tests:UnitTestProject1.UnitTest1 /Logger:trx" -output:"C:\temp\ConsoleApplication1\OpenCover\5f39417c-6b7c-4b4e-8576-a1a8f537ab59\26e9ba67-bd63-48f0-ad8c-2c5a84d18aed.xml" -hideskipped:All -register:user
1 tests found
Executing: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 12.0.30723.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test discovery, please wait...
Passed   TestMethod1
Results File: C:\temp\ConsoleApplication1\OpenCover\5f39417c-6b7c-4b4e-8576-a1a8f537ab59\TestResults\User_PC 2015-07-19 19_36_27.trx

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 0,2494 Seconds
Committing...
Visited Classes 1 of 2 (50)
Visited Methods 1 of 2 (50)
Visited Points 3 of 5 (60)
Visited Branches 1 of 2 (50)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 2 of 3 (66.67)
Alternative Visited Methods 3 of 6 (50)


There is an error in XML document (54, 21).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at OpenCover.UI.Processors.TestExecutor.GetExecutionResults()
```

Results in a XML of:
```xml
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary numSequencePoints="5" visitedSequencePoints="3" numBranchPoints="2" visitedBranchPoints="1" sequenceCoverage="60" branchCoverage="50" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" visitedClasses="1" numClasses="2" visitedMethods="1" numMethods="2" />
  <Modules>
    <Module hash="67-90-75-6A-36-34-3A-41-03-B6-6A-B7-9B-51-1E-A3-6C-71-CA-DA">
      <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="1" numClasses="1" visitedMethods="1" numMethods="1" />
      <FullName>C:\temp\ConsoleApplication1\UnitTestProject1\bin\Debug\UnitTestProject1.dll</FullName>
      <ModuleName>UnitTestProject1</ModuleName>
      <Files>
        <File uid="1" fullPath="c:\temp\ConsoleApplication1\UnitTestProject1\UnitTest1.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="1" numClasses="1" visitedMethods="1" numMethods="1" />
          <FullName>UnitTestProject1.UnitTest1</FullName>
          <Methods>
            <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="100" branchCoverage="100" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken>100663297</MetadataToken>
              <Name>System.Void UnitTestProject1.UnitTest1::TestMethod1()</Name>
              <FileRef uid="1" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="1" ordinal="0" offset="0" sl="12" sc="9" el="12" ec="10" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="1" uspid="2" ordinal="1" offset="1" sl="13" sc="13" el="13" ec="42" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="1" uspid="3" ordinal="2" offset="7" sl="14" sc="9" el="14" ec="10" bec="0" bev="0" fileid="1" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="1" uspid="1" ordinal="0" offset="0" sl="12" sc="9" el="12" ec="10" bec="0" bev="0" fileid="1" />
            </Method>
            <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
              <MetadataToken>100663298</MetadataToken>
              <Name>System.Void UnitTestProject1.UnitTest1::.ctor()</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="1" uspid="4" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
    <Module hash="36-84-04-5F-68-B8-85-C6-6E-2A-DD-A2-4B-B5-01-D6-B8-7B-04-20">
      <Summary numSequencePoints="2" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="1" />
      <FullName>C:\temp\ConsoleApplication1\UnitTestProject1\bin\Debug\ConsoleApplication1.exe</FullName>
      <ModuleName>ConsoleApplication1</ModuleName>
      <Files>
        <File uid="3" fullPath="c:\temp\ConsoleApplication1\ConsoleApplication1\Program.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
          <FullName>ConsoleApplication1.MyEventHandler</FullName>
          <Methods>
            <Method skippedDueTo="Unknown" visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
              <MetadataToken>100663297</MetadataToken>
              <Name>System.Void ConsoleApplication1.MyEventHandler::.ctor(System.Object,System.IntPtr)</Name>
            </Method>
            <Method skippedDueTo="Unknown" visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <MetadataToken>100663298</MetadataToken>
              <Name>System.Void ConsoleApplication1.MyEventHandler::Invoke(ConsoleApplication1.Program,System.EventArgs)</Name>
            </Method>
            <Method skippedDueTo="Unknown" visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <MetadataToken>100663299</MetadataToken>
              <Name>System.IAsyncResult ConsoleApplication1.MyEventHandler::BeginInvoke(ConsoleApplication1.Program,System.EventArgs,System.AsyncCallback,System.Object)</Name>
            </Method>
            <Method skippedDueTo="Unknown" visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <MetadataToken>100663300</MetadataToken>
              <Name>System.Void ConsoleApplication1.MyEventHandler::EndInvoke(System.IAsyncResult)</Name>
            </Method>
          </Methods>
        </Class>
        <Class>
          <Summary numSequencePoints="2" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="1" />
          <FullName>ConsoleApplication1.Program</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="2" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="2" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
              <MetadataToken>100663301</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::add_aEvent(ConsoleApplication1.MyEventHandler)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="5" ordinal="0" offset="0" />
            </Method>
            <Method visited="false" cyclomaticComplexity="2" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="2" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
              <MetadataToken>100663302</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::remove_aEvent(ConsoleApplication1.MyEventHandler)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="6" ordinal="0" offset="0" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="true" isGetter="false" isSetter="false">
              <Summary numSequencePoints="2" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" />
              <MetadataToken>100663303</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::Main(System.String[])</Name>
              <FileRef uid="3" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="7" ordinal="0" offset="0" sl="18" sc="9" el="18" ec="10" bec="0" bev="0" fileid="3" />
                <SequencePoint vc="0" uspid="8" ordinal="1" offset="1" sl="19" sc="9" el="19" ec="10" bec="0" bev="0" fileid="3" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="7" ordinal="0" offset="0" sl="18" sc="9" el="18" ec="10" bec="0" bev="0" fileid="3" />
            </Method>
            <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
              <MetadataToken>100663304</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::.ctor()</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="1" uspid="9" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
  </Modules>
</CoverageSession>
```

**Comment by pver** [comment]
I could not reproduce it yet with my setup, but it might be caused by a different OpenCover version (I don't have the "skippedDueTo="Unknown"" in my result xml). 
Do you know which OpenCover version you have installed? Maybe @sawilde has an idea of why the methods are skipped.

But this situation is definitely something we should catch in OpenCover.UI as well. I'll use your output for now to support this case.

For reference, this is the result xml I got for the same code and unit test (using OpenCover Version 4.5.3522) :
```xml
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary numSequencePoints="5" visitedSequencePoints="3" numBranchPoints="2" visitedBranchPoints="1" sequenceCoverage="60" branchCoverage="50" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" />
  <Modules>
    <Module hash="21-6E-57-CF-53-5A-3C-52-01-FC-BD-F0-19-31-3E-99-74-EC-A4-A8">
      <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
      <FullName>C:\Development\BuilderPatternPoc\BuilderPatternPoc\UnitTestProject2\bin\Debug\UnitTestProject2.dll</FullName>
      <ModuleName>UnitTestProject2</ModuleName>
      <Files>
        <File uid="1" fullPath="c:\Development\BuilderPatternPoc\BuilderPatternPoc\UnitTestProject2\UnitTest1.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
          <FullName>UnitTestProject2.UnitTest1</FullName>
          <Methods>
            <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="100" branchCoverage="100" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663297</MetadataToken>
              <Name>System.Void UnitTestProject2.UnitTest1::TestMethod1()</Name>
              <FileRef uid="1" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="1" ordinal="0" offset="0" sl="12" sc="9" el="12" ec="10" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="1" uspid="2" ordinal="1" offset="1" sl="13" sc="13" el="13" ec="39" bec="0" bev="0" fileid="1" />
                <SequencePoint vc="1" uspid="3" ordinal="2" offset="7" sl="14" sc="9" el="14" ec="10" bec="0" bev="0" fileid="1" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="1" uspid="1" ordinal="0" offset="0" sl="12" sc="9" el="12" ec="10" bec="0" bev="0" fileid="1" />
            </Method>
            <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663298</MetadataToken>
              <Name>System.Void UnitTestProject2.UnitTest1::.ctor()</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="1" uspid="4" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
    <Module hash="B0-AC-86-85-A4-96-D8-3E-B5-2E-3A-87-CF-EF-35-06-EB-82-87-E3">
      <Summary numSequencePoints="2" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" />
      <FullName>C:\Development\BuilderPatternPoc\BuilderPatternPoc\UnitTestProject2\bin\Debug\ConsoleApplication1.exe</FullName>
      <ModuleName>ConsoleApplication1</ModuleName>
      <Files>
        <File uid="3" fullPath="c:\Development\BuilderPatternPoc\BuilderPatternPoc\ConsoleApplication1\Program.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" />
          <FullName>ConsoleApplication1.MyEventHandler</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663297</MetadataToken>
              <Name>System.Void ConsoleApplication1.MyEventHandler::.ctor(System.Object,System.IntPtr)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="5" ordinal="0" offset="0" />
            </Method>
            <Method visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663298</MetadataToken>
              <Name>System.Void ConsoleApplication1.MyEventHandler::Invoke(ConsoleApplication1.Program,System.EventArgs)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="6" ordinal="0" offset="0" />
            </Method>
            <Method visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663299</MetadataToken>
              <Name>System.IAsyncResult ConsoleApplication1.MyEventHandler::BeginInvoke(ConsoleApplication1.Program,System.EventArgs,System.AsyncCallback,System.Object)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="7" ordinal="0" offset="0" />
            </Method>
            <Method visited="false" cyclomaticComplexity="0" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663300</MetadataToken>
              <Name>System.Void ConsoleApplication1.MyEventHandler::EndInvoke(System.IAsyncResult)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="8" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
        <Class>
          <Summary numSequencePoints="2" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" />
          <FullName>ConsoleApplication1.Program</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="2" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="2" />
              <MetadataToken>100663301</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::add_aEvent(ConsoleApplication1.MyEventHandler)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="9" ordinal="0" offset="0" />
            </Method>
            <Method visited="false" cyclomaticComplexity="2" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="2" />
              <MetadataToken>100663302</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::remove_aEvent(ConsoleApplication1.MyEventHandler)</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="10" ordinal="0" offset="0" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="true" isGetter="false" isSetter="false">
              <Summary numSequencePoints="2" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663303</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::Main(System.String[])</Name>
              <FileRef uid="3" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="11" ordinal="0" offset="0" sl="17" sc="9" el="17" ec="10" bec="0" bev="0" fileid="3" />
                <SequencePoint vc="0" uspid="12" ordinal="1" offset="1" sl="18" sc="9" el="18" ec="10" bec="0" bev="0" fileid="3" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="11" ordinal="0" offset="0" sl="17" sc="9" el="17" ec="10" bec="0" bev="0" fileid="3" />
            </Method>
            <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
              <MetadataToken>100663304</MetadataToken>
              <Name>System.Void ConsoleApplication1.Program::.ctor()</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="1" uspid="13" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
  </Modules>
</CoverageSession>
```

**Comment by meolus** [comment]
Thanks for caring about the problem. I've had installed OpenCover (Release) 4.6.166.

Additional I figured out that the problem does not occur with OpenCover 4.5.3427.

**Comment by sawilde** [comment]
It's the state when the 3rd party library we use `Mono.Cecil` fails to get the method body https://github.com/OpenCover/opencover/commit/ea110c595ae2810310558ed8e6b1812d3aa496e0

The library is changing a lot of late with VS2015 support so it may be useful to repeat this and then raise it with them.

**Comment by pver** [comment]
Ok, thanks for the info @meolus and @sawilde! 
I'll first add support for the new SkippedMethod enum values, to make sure the plugin doesn't crash on them anymore (OpenCover.UI should support these new values). And then I'll see if I can figure out why the new Mono.Cecil has problems with it.

**Comment by pver** [comment]
@meolus could you do a test with the version from this build: https://ci.appveyor.com/project/sawilde/opencover-ui/build/1.0.73/artifacts
(you may need to uninstall the official release build before installing this snapshot release, because we didn't increase the version number yet).

I could reproduce the issue you had with OpenCover 4.6.166, and with the fix implemented in #84 it seems to work fine now on my machine.

**Comment by meolus** [comment]
The same for me. With OpenCover 4.6.166 and the version @pver provided, the problem does not occur anymore. Thank you very much for the quick solution.

**Comment by pver** [comment]
Great, thank you too for helping with troubleshooting and testing!
I'll check with the others when we cab make a new release that contains this fix
